RUN_STRINGS = (
    "Sekarang kamu melihatku, sekarang kamu tidak."  "ε=ε=ε=ε=┌(;￣▽￣)┘" ,
    "Kembali kesini!" ,
    "REEEEEEEEEEEEEEEEEE!!!!!!!!" ,
    "Awas tembok!" ,
    "Jangan tinggalkan aku sendiri dengan mereka!!" ,
    "Kamu punya teman!" ,
    "Chottomatte!" ,
    "Yare yare linglung" ,
    "*Naruto run diaktifkan*" ,
    "*Nezuko dijalankan diaktifkan*" ,
    "Hah? apa? mereka kabur?" ,
    "Kembali kesini!" ,
    "Awas tembok!" ,
    "Jangan tinggalkan aku sendiri dengan mereka!!" ,
    "Kamu punya teman!" ,
    "Chottomatte!" ,
    "Yare yare linglung" ,
    "Hei, bertanggung jawab atas apa yang baru saja kamu lakukan!" ,
    "Semoga peluang selalu menguntungkan Anda." ,
    "Lari semuanya, mereka baru saja menjatuhkan bom 💣💣" ,
    "Dan mereka menghilang selamanya, tidak pernah terlihat lagi." ,
    "Legenda mengatakannya, mereka masih berlari." ,
    "Hasta la vista, sayang." ,
    "Ah, sayang sekali. Aku suka yang itu." ,
    "Seperti kata Dokter... LARI!" ,
)

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

SLAP_SAITAMA_TEMPLATES = (
    "Slap me one more time and I'll mute you.",
    "Stop slapping me. REEEEEEEEEEEEEE.",
    [
        "I am muting you for a minute.",  # normal reply
        "Stop slapping me just because I can't mute you. REEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Shut up!",
        "Silence!",
    ],
)

SLAP_TEMPLATES = (
    "{user2} dibunuh oleh sihir." ,
    "{user2} kelaparan tanpa tepukan." ,
    "{user2} dijatuhkan ke dalam kekosongan oleh {user1}." ,
    "{user2} pingsan." ,
    "{user2} kehabisan Pokemon yang bisa digunakan! {user2} mati total!." ,
    "{user2} kehabisan Pokemon yang bisa digunakan! {user2} pingsan!." ,
    "{user2} punya rekt." ,
    "Melon {user2} dibelah oleh {user1}." ,
    "{user2} diiris dan dipotong dadu oleh {user1}." ,
    "{user2} bermain hot-potato dengan granat." ,
    "{user2} ditusuk oleh {user1}." ,
    "{user2} makan granat." ,
    "{user2} untuk makan malam!" ,
    "{user2} dihentikan oleh {user1}." ,
    "{user1} mengirim spam ke email {user2}." ,
    "{user1} mengenkripsi RSA {user2} dan menghapus kunci pribadi." ,
    "{user1} tempatkan {user2} di zona pertemanan." ,
    "{user1} menampar {user2} dengan permintaan penghapusan DMCA!" ,
    "{user2} mendapat telepon rumah dari Dokter {user1}." ,
    "{user1} memenggal {user2}." ,
    "{user2} dilempari batu...oleh massa yang marah." ,
    "{user1} menggugat celana {user2}." ,
    "{user2} adalah KO satu pukulan oleh {user1}." ,
    "{user1} mengirim {user2} ke lubang memori." ,
    "{user2} adalah sebuah kesalahan. - '{user1}' " ,
    "{user2} dibuat mubazir." ,
    "{user1} {hits} {user2} dengan kelelawar!." ,
    "{user1} {hits} {user2} dengan Jurus Taijutsu!." ,
    "{user1} {hits} {user2} dengan X-Gloves!." ,
    "{user1} {hits} {user2} dengan Jet Punch!." ,
    "{user1} {hits} {user2} dengan Jet Pistol!." ,
    "{user1} {hits} {user2} dengan United States of Smash!." ,
    "{user1} {hits} {user2} dengan Detroit Smash!." ,
    "{user1} {hits} {user2} dengan Texas Smash!." ,
    "{user1} {hits} {user2} dengan California Smash!." ,
    "{user1} {hits} {user2} dengan New Hampshire Smash!." ,
    "{user1} {hits} {user2} dengan Missouri Smash!." ,
    "{user1} {hits} {user2} dengan Carolina Smash!." ,
    "{user1} {hits} {user2} dengan King Kong Gun!." ,
    "{user1} {hits} {user2} dengan tongkat bisbol - logam.!." ,
    "* Pukulan serius {user2}*." ,
    "* Pukulan biasa {user2}*." ,
    "* Pukulan normal berturut-turut {user2}*." ,
    "* Pukulan Normal Dua Tangan Berturut-turut {user2}*." ,
    "*Abaikan {user2} untuk membiarkan mereka mati karena malu*." ,
    "* menunjuk ke {user2}* Ada apa dengan lancang... anak hilang ini?." ,
    "*Pukul {user2} dengan Fire Tornado*." ,
    "{user1} menusuk mata {user2}!" ,
    "{user1} menyodok {user2} di samping!" ,
    "{user1} colek {user2}!" ,
    "{user1} menusuk {user2} dengan jarum!" ,
    "{user1} menusuk {user2} dengan pena!" ,
    "{user1} menusuk {user2} dengan senjata bius!" ,
    "{user2} diam-diam adalah Furry!" ,
    "Hai Semuanya! {user1} meminta saya untuk menjadi jahat!" ,
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}" ,
    "Ambil ini {user2} \n (ﾉﾟДﾟ)ﾉ ))))●~* " ,
    "Sini {user2} pegang ini \n (｀・ω・)つ ●~＊" ,
    "( ・_・)ノΞ●~* {user2} \n Dieeeeee!!." ,
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n *Bug menyemprot {user2}*." ,
    "( ﾟДﾟ)ﾉ占~<巛巛巛. \n -{user2} Kamu menyebalkan!" ,
    r"( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} dengan {item}." ,
    "{user1} {hits} {user2} di muka dengan {item}." ,
    "{user1} {hits} {user2} sedikit dengan {item}." ,
    "{user1} {throws} {item} ke {user2}." ,
    "{user1} mengambil {item} dan {throws} ke wajah {user2}." ,
    "{user1} meluncurkan {item} ke arah umum {user2}." ,
    "{user1} mulai menampar {user2} konyol dengan {item}." ,
    "{user1} menyematkan {user2} ke bawah dan berulang kali {hits} mereka dengan {item}." ,
    "{user1} mengambil {item} dan {hits} {user2} dengan itu." ,
    "{user1} mengikat {user2} ke kursi dan {throws} {item} ke arah mereka." ,
    "{user1} memberikan dorongan ramah untuk membantu {user2} belajar berenang di lahar." ,
    "{user1} menindas {user2}." ,
    "Nyaan memakan kaki {user2}. *nomnomnom*" ,
    "{user1} {throws} bola master ke {user2}, perlawanan sia-sia." ,
    "{user1} mengenai {user2} dengan action beam...bbbbbb (ง・ω・)ง ====*" ,
    "{user1} ara ara {user2}." ,
    "{user1} ora ora {user2}." ,
    "{user1} muda muda {user2}." ,
    "{user2} diubah menjadi referensi Jojo!" ,
    "{user1} memukul {user2} dengan {item}." ,
    "Ronde 2!..Siap?.. FIGHT!!" ,
    "WhoPixel akan menghasilkan {user2} hingga tak terbatas dan seterusnya." ,
    "{user2} makan kelelawar dan menemukan penyakit baru." ,
    "{user1} melipat {user2} menjadi bidang kertas" ,
    "{user1} menghidangkan {user2} sup kelelawar." ,
    "{user2} dikirim ke rumah mereka, planet kera." ,
    "{user1} menendang {user2} dari kereta yang bergerak." ,
    "{user2} baru saja membunuh anjing John Wick." ,
    "{user1} melakukan mantra Avada Kedavra pada {user2}." ,
    "{user1} membuat {user2} menjadi tungku api." ,
    "Sakura Haruno menjadi lebih berguna daripada {user2}" ,
    "{user1} mencabut dukungan hidup {user2}." ,
    "{user1} berlangganan {user2}' ke internet buruk selama 5 tahun." ,
    "Kamu tahu apa yang lebih buruk dari lelucon Ayah? {user2}!" ,
    "{user1} mengambil semua cookie {user2}." ,
    "{user2} wa mou.......Shindeiru! - {user1}." ,
    "{user2} kehilangan bidak ras mereka!" ,  
    "Diam {user2}, kamu hanya {user2}." ,
    "{user1} memukul {user2} dengan Aka si anse!" ,  
    "@NeoTheKitty mencakar {user2}",   
    "Majin buu makan {user2}",
    "Pembunuh Goblin membunuh {user2}", 
)

PAT_TEMPLATES = (
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    "Oh no! We are all out of pats.",
    "This is a designated no pat zone!",
    "No pats for {user2}!",
    "{user1} spoils {user2} with headpats!",
    "{user2} received one free headpat!",
    "{user1} headpats {user2} whilst giving a lap pillow",
    "{user1} aggressively pats {user2}",
    "{user1} gently strokes {user2}'s head",
    "Pat, pat, pat, pat",
    "{user2} could not escape {user1}'s headpats",
    "{user2}.exe has stopped working",
    "{user1} rubs {user2} on the neck",
    "Must... extort... HEADPATS",
    "{user1} headpats {user2}'s head with a pat",
    "{user1} pats {user2} unexpectedly",
    "{user1} pats {user2} with consent, maybe?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} pats {user2} friendlily",
    "{user2} uses HEADPATS? O KAWAII KOTO",
    "*headpats.gif intensifies for {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = (
    "PONG!!",
    "I am here!",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("Heads", "Tails")

EIGHTBALL = [
    "🟢 As I see it, yes.",
    "🟡 Ask again later.",
    "🟡 Better not tell you now.",
    "🟡 Cannot predict now.",
    "🟡 Concentrate and ask again.",
    "🟡 Don’t count on it.",
    "🟢 It is certain.",
    "🟢 It is decidedly so.",
    "🟢 Most likely.",
    "🔴 My reply is no.",
    "🔴 My sources say no.",
    "🔴 Outlook not so good.",
    "🟢 Outlook good.",
    "🟡 Reply hazy, try again.",
    "🟢 Signs point to yes.",
    "🔴 Very doubtful.",
    "🟢 Without a doubt.",
    "🟢 Yes.",
    "🟢 Yes – definitely.",
    "🟢 You may rely on it.",
]

DECIDE = ("Yes.", "No.", "Maybe.")

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "I ran out of tables, will order more.",
    "Go do some work instead of flippin tables.",
)
